"""L2 unit tests for eqsl-mcp — all 5 tools + parser + date helpers.

Uses EQSL_MCP_MOCK=1 for tool-level tests (no eQSL API calls).
Direct unit tests on parser and date helper functions.

Test IDs: EQSL-L2-001 through EQSL-L2-045
"""

from __future__ import annotations

import os
from datetime import date

import pytest

os.environ["EQSL_MCP_MOCK"] = "1"

from eqsl_mcp.parser import FetchResult, parse_adif, to_mmddyyyy, to_qso, to_yyyymmddhhmm
from eqsl_mcp.server import (
    eqsl_ag_check,
    eqsl_download,
    eqsl_inbox,
    eqsl_last_upload,
    eqsl_verify,
)


# ---------------------------------------------------------------------------
# EQSL-L2-001..010: ADIF parser (parse_adif)
# ---------------------------------------------------------------------------


class TestParseAdif:
    def test_single_record(self):
        """EQSL-L2-001: Parse one complete ADIF record."""
        adif = "<CALL:5>KI7MT<BAND:3>20M<EOR>"
        recs = parse_adif(adif)
        assert len(recs) == 1
        assert recs[0]["CALL"] == "KI7MT"
        assert recs[0]["BAND"] == "20M"

    def test_multiple_records(self):
        """EQSL-L2-002: Parse two records separated by EOR."""
        adif = "<CALL:5>KI7MT<EOR><CALL:4>W1AW<EOR>"
        recs = parse_adif(adif)
        assert len(recs) == 2
        assert recs[0]["CALL"] == "KI7MT"
        assert recs[1]["CALL"] == "W1AW"

    def test_case_insensitive_tags(self):
        """EQSL-L2-003: Tags stored uppercase regardless of input case."""
        adif = "<call:5>KI7MT<eor>"
        recs = parse_adif(adif)
        assert recs[0]["CALL"] == "KI7MT"

    def test_empty_string(self):
        """EQSL-L2-004: Empty string returns empty list."""
        assert parse_adif("") == []

    def test_no_eor(self):
        """EQSL-L2-005: Record without EOR still captured."""
        adif = "<CALL:5>KI7MT<BAND:3>20M"
        recs = parse_adif(adif)
        assert len(recs) == 1
        assert recs[0]["CALL"] == "KI7MT"

    def test_value_length_respected(self):
        """EQSL-L2-006: Length field controls value extraction."""
        adif = "<CALL:3>KI7MT<EOR>"
        recs = parse_adif(adif)
        # Parser extracts based on length field
        assert len(recs) == 1
        assert recs[0]["CALL"].startswith("KI7")

    def test_data_type_indicator(self):
        """EQSL-L2-007: Optional type indicator handled."""
        adif = "<QSO_DATE:8:D>20260301<EOR>"
        recs = parse_adif(adif)
        assert recs[0]["QSO_DATE"] == "20260301"

    def test_whitespace_between_tags(self):
        """EQSL-L2-008: Whitespace between tags skipped."""
        adif = "  <CALL:5>KI7MT<BAND:3>20M<EOR>  "
        recs = parse_adif(adif)
        assert len(recs) == 1
        assert recs[0]["CALL"].strip() == "KI7MT"

    def test_eor_only(self):
        """EQSL-L2-009: EOR with no fields produces no records."""
        assert parse_adif("<EOR>") == []

    def test_header_skipped(self):
        """EQSL-L2-010: Text before first tag is ignored."""
        adif = "Generated by eQSL\n<CALL:5>KI7MT<EOR>"
        recs = parse_adif(adif)
        assert len(recs) == 1


# ---------------------------------------------------------------------------
# EQSL-L2-011..015: to_qso (record normalization)
# ---------------------------------------------------------------------------


class TestToQso:
    def test_basic_conversion(self):
        """EQSL-L2-011: Raw dict converted to QsoRecord."""
        rec = {"CALL": "KI7MT", "BAND": "20M", "MODE": "FT8"}
        qso = to_qso(rec)
        assert qso["call"] == "KI7MT"
        assert qso["band"] == "20M"
        assert qso["mode"] == "FT8"

    def test_call_uppercased(self):
        """EQSL-L2-012: Callsign normalized to uppercase."""
        qso = to_qso({"CALL": "ki7mt"})
        assert qso["call"] == "KI7MT"

    def test_missing_fields_default(self):
        """EQSL-L2-013: Missing optional fields return None."""
        qso = to_qso({"CALL": "KI7MT"})
        assert qso["band"] is None
        assert qso["gridsquare"] is None

    def test_freq_float_conversion(self):
        """EQSL-L2-014: FREQ field converted to float."""
        qso = to_qso({"CALL": "KI7MT", "FREQ": "14.074"})
        assert qso["freq"] == pytest.approx(14.074)

    def test_invalid_freq(self):
        """EQSL-L2-015: Invalid FREQ returns None."""
        qso = to_qso({"CALL": "KI7MT", "FREQ": "abc"})
        assert qso["freq"] is None


# ---------------------------------------------------------------------------
# EQSL-L2-016..020: Date helpers
# ---------------------------------------------------------------------------


class TestDateHelpers:
    def test_to_yyyymmddhhmm_iso(self):
        """EQSL-L2-016: ISO date string converted."""
        result = to_yyyymmddhhmm("2026-03-01")
        assert result == "202603010000"

    def test_to_yyyymmddhhmm_date_obj(self):
        """EQSL-L2-017: date object converted."""
        result = to_yyyymmddhhmm(date(2026, 3, 1))
        assert result == "202603010000"

    def test_to_yyyymmddhhmm_none(self):
        """EQSL-L2-018: None returns 30 days ago."""
        result = to_yyyymmddhhmm(None)
        assert len(result) == 12
        assert result.endswith("0000")

    def test_to_yyyymmddhhmm_invalid(self):
        """EQSL-L2-019: Invalid string falls back to now."""
        result = to_yyyymmddhhmm("not-a-date")
        assert len(result) == 12

    def test_to_mmddyyyy_valid(self):
        """EQSL-L2-020: ISO date to MM/DD/YYYY."""
        assert to_mmddyyyy("2026-03-01") == "03/01/2026"

    def test_to_mmddyyyy_invalid(self):
        """EQSL-L2-021: Invalid date returns input unchanged."""
        assert to_mmddyyyy("not-a-date") == "not-a-date"


# ---------------------------------------------------------------------------
# EQSL-L2-022..030: Tool mock-mode tests (eqsl_inbox)
# ---------------------------------------------------------------------------


class TestEqslInbox:
    def test_returns_records(self):
        """EQSL-L2-022: Inbox returns 2 mock records."""
        result = eqsl_inbox(persona="test")
        assert result["total"] == 2
        assert len(result["records"]) == 2

    def test_confirmed_only(self):
        """EQSL-L2-023: confirmed_only filters to QSL_RCVD=Y."""
        result = eqsl_inbox(persona="test", confirmed_only=True)
        assert result["total"] == 1
        assert result["records"][0]["call"] == "KI7MT"

    def test_unconfirmed_only(self):
        """EQSL-L2-024: unconfirmed_only filters to QSL_RCVD!=Y."""
        result = eqsl_inbox(persona="test", unconfirmed_only=True)
        assert result["total"] == 1
        assert result["records"][0]["call"] == "K7ABC"

    def test_band_tally(self):
        """EQSL-L2-025: Band tally groups correctly."""
        result = eqsl_inbox(persona="test")
        bands = {b["band"]: b["count"] for b in result["by_band"]}
        assert bands["20M"] == 1
        assert bands["40M"] == 1

    def test_record_fields(self):
        """EQSL-L2-026: Records have expected QSO fields."""
        result = eqsl_inbox(persona="test")
        rec = result["records"][0]
        for field in ("call", "qso_date", "band", "mode"):
            assert field in rec, f"Missing field: {field}"


# ---------------------------------------------------------------------------
# EQSL-L2-031..035: eqsl_download
# ---------------------------------------------------------------------------


class TestEqslDownload:
    def test_returns_raw_adif(self):
        """EQSL-L2-031: Download returns raw ADIF text."""
        result = eqsl_download(persona="test")
        assert "adif" in result
        assert "<EOR>" in result["adif"].upper()

    def test_record_count(self):
        """EQSL-L2-032: Download reports correct record count."""
        result = eqsl_download(persona="test")
        assert result["record_count"] == 2

    def test_full_history(self):
        """EQSL-L2-033: since=None downloads full history."""
        result = eqsl_download(persona="test", since=None)
        assert result["record_count"] == 2

    def test_adif_contains_callsigns(self):
        """EQSL-L2-034: ADIF text contains expected callsigns."""
        result = eqsl_download(persona="test")
        assert "KI7MT" in result["adif"]
        assert "K7ABC" in result["adif"]


# ---------------------------------------------------------------------------
# EQSL-L2-036..040: eqsl_verify + eqsl_ag_check
# ---------------------------------------------------------------------------


class TestEqslVerify:
    def test_verified(self):
        """EQSL-L2-036: Mock verify returns verified=True."""
        result = eqsl_verify(
            from_call="KI7MT", to_call="W1AW", band="20M", qso_date="2026-03-01"
        )
        assert result["verified"] is True

    def test_ag_status(self):
        """EQSL-L2-037: Mock verify returns ag=True."""
        result = eqsl_verify(
            from_call="KI7MT", to_call="W1AW", band="20M", qso_date="2026-03-01"
        )
        assert result["ag"] is True

    def test_verify_fields(self):
        """EQSL-L2-038: Verify result has expected fields."""
        result = eqsl_verify(
            from_call="KI7MT", to_call="W1AW", band="20M", qso_date="2026-03-01"
        )
        for field in ("verified", "ag", "message"):
            assert field in result, f"Missing field: {field}"


class TestEqslAgCheck:
    def test_returns_callsign(self):
        """EQSL-L2-039: AG check returns callsign."""
        result = eqsl_ag_check(callsign="KI7MT")
        assert result["callsign"] == "KI7MT"
        assert "ag" in result

    def test_uppercase_callsign(self):
        """EQSL-L2-040: AG check uppercases callsign."""
        result = eqsl_ag_check(callsign="ki7mt")
        assert result["callsign"] == "KI7MT"


# ---------------------------------------------------------------------------
# EQSL-L2-041..043: eqsl_last_upload
# ---------------------------------------------------------------------------


class TestEqslLastUpload:
    def test_returns_date(self):
        """EQSL-L2-041: Last upload returns persona and date."""
        result = eqsl_last_upload(persona="test")
        assert result["persona"] == "test"
        assert result["last_upload"] is not None

    def test_upload_date_format(self):
        """EQSL-L2-042: Last upload date is a non-empty string."""
        result = eqsl_last_upload(persona="test")
        assert isinstance(result["last_upload"], str)
        assert len(result["last_upload"]) > 0


# ---------------------------------------------------------------------------
# EQSL-L2-044..045: FetchResult dataclass
# ---------------------------------------------------------------------------


class TestFetchResult:
    def test_immutable(self):
        """EQSL-L2-044: FetchResult is frozen dataclass."""
        fr = FetchResult(records=[])
        with pytest.raises(AttributeError):
            fr.records = []  # type: ignore[misc]

    def test_empty_records(self):
        """EQSL-L2-045: FetchResult accepts empty records list."""
        fr = FetchResult(records=[])
        assert len(fr.records) == 0
